import '../styles/globals.css'
import type {AppProps} from 'next/app'
import DataContextProvider from "../context/DataContext";
import Head from "next/head";
import {Layout} from "../components/Layout";

export default function App({Component, pageProps}: AppProps<{ pageName: string[] }>) {
    const title = `PSVA - ${pageProps.pageName}`
    return (
        <DataContextProvider>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </DataContextProvider>
    )
}
