import '../styles/globals.css'
import type {AppProps} from 'next/app'
import DataContextProvider from "../context/DataContext";
import {MantineProvider} from "@mantine/core";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps<{pageName:string[]}>) {
    const title = `PSVA - ${pageProps.pageName}`
    return (
        <DataContextProvider>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MantineProvider withGlobalStyles withNormalizeCSS theme={{colorScheme: 'dark'}}>
                <Component {...pageProps} />
            </MantineProvider>
        </DataContextProvider>
    )
}
